// In-house library discovery. A library is "in-house" when its installed folder ships a claude-lib.md prompt file,
// so no list of library names is needed. Works for registry installs and for linked checkouts (npm link / file:).
import { existsSync, readFileSync, readdirSync, realpathSync, writeFileSync, unlinkSync, mkdirSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { readJson, pkgJson, existingPackages, allDeps, toPosix } from './detect.mjs';

export const LIB_PROMPT = 'claude-lib.md';
export const GENERATED_MARKER = '<!-- generated by: node .claude/scripts/lib-info.mjs sync-agents. Do not edit; regenerated each session. -->';

const owners = (root) => ['.', ...existingPackages(root)];

const ownerJson = (root, owner) => (owner === '.' ? readJson(join(root, 'package.json')) : pkgJson(root, owner));

// Installed folder of a dependency as seen from owner (owner/node_modules first, then root/node_modules).
export const installedDir = (root, owner, name) => {
  const dirs = owner === '.' ? [root] : [join(root, owner), root];
  for (const dir of dirs) {
    const candidate = join(dir, 'node_modules', ...name.split('/'));
    if (existsSync(join(candidate, 'package.json'))) return candidate;
  }

  return null;
};

const realDir = (dir) => {
  try {
    return realpathSync(dir);
  } catch {
    return dir;
  }
};

// A dependency whose real path leaves node_modules is a linked local checkout (npm link, file:, workspace).
const isLinked = (real) => !real.split(sep).includes('node_modules');

export const parseFrontmatter = (text) => {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  const data = {};
  if (!match) return data;
  for (const line of match[1].split(/\r?\n/)) {
    const kv = line.match(/^([\w-]+)\s*:\s*(.*)$/);
    if (kv) data[kv[1]] = kv[2].replace(/^['"]|['"]$/g, '').trim();
  }

  return data;
};

// One entry per library: where it is installed, its version, who depends on it, and its prompt file (if any).
export const describeLib = (root, name, owner = null) => {
  const searchOwners = owner ? [owner] : owners(root);
  const users = [];
  let dir = null;
  for (const o of searchOwners) {
    const range = allDeps(ownerJson(root, o))[name];
    const installed = installedDir(root, o, name);
    if (range) users.push({ owner: o, range });
    dir ??= installed;
  }
  dir ??= installedDir(root, '.', name);
  if (!dir) return null;
  const json = readJson(join(dir, 'package.json')) ?? {};
  const real = realDir(dir);
  const promptPath = join(dir, LIB_PROMPT);
  const prompt = existsSync(promptPath) ? readFileSync(promptPath, 'utf8') : null;

  return {
    name,
    version: json.version ?? '?',
    dir,
    real,
    linked: isLinked(real),
    users,
    json,
    prompt,
    meta: prompt ? parseFrontmatter(prompt) : {},
  };
};

// All dependencies (of the root and every package) that ship claude-lib.md.
export const discoverLibs = (root) => {
  const names = new Set();
  for (const o of owners(root)) Object.keys(allDeps(ownerJson(root, o))).forEach((n) => names.add(n));

  return [...names]
    .sort()
    .map((n) => describeLib(root, n))
    .filter((lib) => lib?.prompt);
};

export const libSlug = (name) =>
  name
    .replace(/^@/, '')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();

export const agentName = (name) => `lib-${libSlug(name)}`;

const agentFile = (lib) => {
  const summary = lib.meta.summary || `The in-house library ${lib.name}.`;
  const when = lib.meta.whenToUse || `using, upgrading or debugging ${lib.name}`;
  const description = `Expert on the in-house library ${lib.name}: ${summary.replace(/\.$/, '')}. Use proactively when ${when.replace(/\.$/, '')}. Read-only; answers with concrete usage for this repo.`;

  return `---
name: ${agentName(lib.name)}
description: ${JSON.stringify(description)}
tools: Read, Grep, Glob, Bash(node .claude/scripts/lib-info.mjs:*)
model: sonnet
---
${GENERATED_MARKER}

You are the expert on the in-house library \`${lib.name}\`. You are **read-only**: you explain, locate and propose; the main agent edits.

## Always start with
1. \`node .claude/scripts/lib-info.mjs show ${lib.name}\`: the library's own prompt file (claude-lib.md) for the **installed** version, plus its version, path, entry points and peer deps. Treat it as the primary source of truth.
2. Then, as the question needs:
   - \`node .claude/scripts/lib-info.mjs api ${lib.name}\` for the exported symbols from its type declarations.
   - \`node .claude/scripts/lib-info.mjs usage ${lib.name}\` for how this repo already uses it. Prefer matching those patterns.
   - \`node .claude/scripts/lib-info.mjs changes ${lib.name}\` for changelog entries when upgrading or when behavior changed.
3. Read the library's files directly (the path from \`show\`) for details: \`.d.ts\` files, README, and source when it is a linked checkout.

## Rules
- Only state APIs you have seen in the prompt file, the type declarations or the source. Never invent props, options or exports; if something is not there, say so.
- Answer for the installed version. If the prompt file and the types disagree, trust the types and point out the stale prompt file (it is fixed with \`/lib-doc\` in the library repo).
- Never suggest editing files under \`node_modules/\`. A bug or missing feature in the library is fixed in the library's own repo; say what to change there.
- Give code that follows this repo's conventions (see CLAUDE.md and the existing usage sites), with file:line references.
`;
};

// Write .claude/agents/lib-<slug>.md for every discovered library; remove generated agents for libraries that are gone.
// Returns { written: [...], removed: [...] } (only files whose content changed).
export const syncAgents = (root, libs = discoverLibs(root)) => {
  const dir = join(root, '.claude', 'agents');
  mkdirSync(dir, { recursive: true });
  const written = [];
  const removed = [];
  const keep = new Set();
  for (const lib of libs) {
    const file = join(dir, `${agentName(lib.name)}.md`);
    keep.add(file);
    const content = agentFile(lib);
    const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
    if (current !== null && !current.includes(GENERATED_MARKER)) continue; // hand-written agent with the same name wins
    if (current !== content) {
      writeFileSync(file, content);
      written.push(toPosix(relative(root, file)));
    }
  }
  for (const f of readdirSync(dir)) {
    const file = join(dir, f);
    if (!/^lib-.*\.md$/.test(f) || keep.has(file)) continue;
    if (readFileSync(file, 'utf8').includes(GENERATED_MARKER)) {
      unlinkSync(file);
      removed.push(toPosix(relative(root, file)));
    }
  }

  return { written, removed };
};
