// Skills, agents and the new-endpoint templates stay consistent with the repo: references resolve, frontmatter is
// valid, and the template code passes the same hooks (style-advice, guard-boundaries) that code written from it meets.
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { runHook, makeRepo, cleanup, HOOKS_DIR } from './helpers.mjs';

const ROOT = join(HOOKS_DIR, '..', '..');
const CLAUDE = join(ROOT, '.claude');
const SKILLS = join(CLAUDE, 'skills');
const AGENTS = join(CLAUDE, 'agents');
const TEMPLATES = join(SKILLS, 'new-endpoint', 'templates');
const GENERATED = '<!-- generated by:';
const read = (file) => readFileSync(file, 'utf8').replace(/\r\n/g, '\n');

const frontmatter = (text) => {
  const block = text.match(/^---\n([\s\S]*?)\n---\n/)?.[1] ?? '';

  return Object.fromEntries(block.split('\n').map((l) => l.match(/^(\w[\w-]*):\s*(.*)$/)).filter(Boolean).map((m) => [m[1], m[2]]));
};

const skillNames = readdirSync(SKILLS, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name);
const agentFiles = readdirSync(AGENTS).filter((f) => f.endsWith('.md') && !read(join(AGENTS, f)).includes(GENERATED));
const agentNames = agentFiles.map((f) => basename(f, '.md'));
const docs = [
  ...skillNames.flatMap((s) => {
    const dir = join(SKILLS, s);
    const templates = existsSync(join(dir, 'templates')) ? readdirSync(join(dir, 'templates')).map((t) => join(dir, 'templates', t)) : [];

    return [join(dir, 'SKILL.md'), ...templates];
  }),
  ...agentFiles.map((f) => join(AGENTS, f)),
  join(ROOT, 'CLAUDE.md'),
  ...['client', 'server', 'db', 'utils'].map((p) => join(ROOT, p, 'CLAUDE.md')).filter(existsSync),
];
const rel = (file) => file.slice(ROOT.length + 1).replace(/\\/g, '/');

for (const name of skillNames) {
  test(`skill ${name}: SKILL.md frontmatter`, () => {
    const fm = frontmatter(read(join(SKILLS, name, 'SKILL.md')));

    assert.equal(fm.name, name);
    assert.ok(fm.description, 'description is missing');
  });
}

for (const name of agentNames) {
  test(`agent ${name}: frontmatter`, () => {
    const fm = frontmatter(read(join(AGENTS, `${name}.md`)));

    assert.equal(fm.name, name);
    assert.ok(fm.description, 'description is missing');
    assert.ok(fm.tools, 'tools are missing');
  });
}

// Paths that exist only at runtime or only in a project.
const RUNTIME_PATHS = /^\.claude\/(logs|scratch)\/|^\.claude\/settings\.local\.json$|^\.claude\/template-manifest\.json$/;

for (const file of docs) {
  test(`${rel(file)}: references resolve`, () => {
    const text = read(file);
    const missing = [];
    for (const [, path] of text.matchAll(/(\.claude\/[\w./-]*\w\.(?:md|mjs|json))/g)) {
      if (!RUNTIME_PATHS.test(path) && !existsSync(join(ROOT, path))) missing.push(path);
    }
    if (file.startsWith(join(SKILLS, ''))) {
      const skillDir = join(SKILLS, rel(file).split('/')[2]);
      for (const [, t] of text.matchAll(/(?<![\w/])templates\/([\w.-]+\.md)/g)) {
        if (!existsSync(join(skillDir, 'templates', t))) missing.push(`templates/${t}`);
      }
    }
    for (const [, skill] of text.matchAll(/`\/([a-z][a-z-]*)`/g)) {
      if (!skillNames.includes(skill)) missing.push(`/${skill}`);
    }
    for (const [, agent] of text.matchAll(/`([a-z]+(?:-[a-z]+)*-(?:reviewer|runner|guard|expert))`/g)) {
      if (!agentNames.includes(agent)) missing.push(`agent ${agent}`);
    }

    assert.deepEqual(missing, []);
  });
}

// Template code blocks: the file each one becomes. A `// <path>` first line wins; otherwise the default below.
const DEFAULT_PATHS = {
  'client-hook.test.md': 'client/src/hooks/useUserMatches.test',
  'db-repo.ts.md': 'db/src/repositories/matches.repo.ts',
  'db-repo.test.ts.md': 'db/src/repositories/matches.repo.test.ts',
  'server.test.ts.md': 'server/src/routes/matches.test.ts',
  'utils-schema.ts.md': 'utils/src/schemas/matches.ts',
  'utils-schema.test.ts.md': 'utils/src/schemas/matches.test.ts',
};
const LANG_EXT = { ts: '.ts', tsx: '.tsx', js: '.js', jsx: '.jsx' };

const fences = readdirSync(TEMPLATES).flatMap((template) =>
  [...read(join(TEMPLATES, template)).matchAll(/^```(tsx?|jsx?)\n([\s\S]*?)^```/gm)].map(([, lang, code], i) => {
    const first = code.match(/^\/\/ ((?:client|server|db|utils)\/\S+\.[cm]?[jt]sx?)\n/)?.[1];
    const fallback = DEFAULT_PATHS[template];
    const path = first ?? (fallback && (/\.[jt]sx?$/.test(fallback) ? fallback : `${fallback}${LANG_EXT[lang]}`));
    const source = code.replaceAll('<utils package name>', '@app/utils').replaceAll('<db package name>', '@app/db');

    return { template, index: i + 1, lang, path, source };
  }),
);

let repo;
before(() => {
  repo = makeRepo({
    committed: {
      'client/package.json': { name: 'client' },
      'server/package.json': { name: 'server' },
      'db/package.json': { name: '@app/db', dependencies: { 'drizzle-orm': '*' } },
      'utils/package.json': { name: '@app/utils' },
    },
  });
});
after(() => cleanup(repo));

const writeEvent = (event, path, content) => ({ hook_event_name: event, tool_name: 'Write', tool_input: { file_path: join(repo, path), content } });
// TS-only syntax: annotations after a parameter or binding, interface/type declarations, `as` casts, generics on calls.
const TS_SYNTAX = /\b(interface|type)\s+[A-Z]\w*\s*[={<]|\)\s*:\s*[A-Z][\w<>[\]|. ]*\s*=>|\b\w+\s*:\s*(string|number|boolean|unknown|void|[A-Z]\w*(<[^>]*>)?)\s*[,)=]|\sas\s+(const|[A-Z]\w*|never|unknown)\b|\b\w+<[A-Z]\w*>\(/;

for (const { template, index, lang, path, source } of fences) {
  const label = `${template} block ${index}`;

  test(`${label}: has a target path`, () => {
    assert.ok(path, `add a "// <pkg>/src/..." first line or a DEFAULT_PATHS entry for ${template}`);
  });
  if (!path) continue;

  test(`${label} (${path}): no style notes`, () => {
    const res = runHook('style-advice.mjs', writeEvent('PostToolUse', path, source), repo);

    assert.equal(res.code, 0, res.stderr);
    assert.equal(res.stdout, '', res.stdout && JSON.parse(res.stdout).hookSpecificOutput.additionalContext);
  });

  test(`${label} (${path}): not blocked by guard-boundaries`, () => {
    const res = runHook('guard-boundaries.mjs', writeEvent('PreToolUse', path, source), repo);

    assert.equal(res.code, 0, res.stderr);
  });

  if (lang === 'js' || lang === 'jsx') {
    test(`${label}: no TypeScript syntax in a JS block`, () => {
      const hit = source.split('\n').find((line) => !/^\s*\/\//.test(line) && TS_SYNTAX.test(line));

      assert.equal(hit, undefined);
    });
  }
}
